version: "3"

services:
  allchat:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ".:/home/caiogallo/Documents/allchat"

  redis:
    image: "redis"

    command: redis-server /home/caiogallo/Documents/allchat/redis.conf

    ports:
     - "6379:6379"

    volumes:
     - ./redis-data:/home/caiogallo/Documents/redis-data
     - ./redis.conf:/home/caiogallo/Documents/allchat/redis.conf
