version: "3"

services:
  allchat:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      # Linux dir
      # - ".:/home/caiogallo/Documents/allchat"
      # Mac dir
      - ".:/Users/caiogallo/documents/allchat"

  # redis:
  #   image: "redis"

  #   command: redis-server /home/caiogallo/Documents/allchat/redis.conf

  #   ports:
  #    - "6379:6379"

  #   volumes:
  #    - ./redis-data:/home/caiogallo/Documents/redis-data
  #    - ./redis.conf:/home/caiogallo/Documents/allchat/redis.conf

    #  GET IP OF REDIS
    #  docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' container_name_or_id